baseURL = "https://noster.dev/"
languageCode = "en-us"
title = "Kamil Noster"
theme = "console"

[params]
  description = "Software Developer Portfolio"
  author = "Kamil Noster"
  titleCutting = true
  animateStyle = "animated zoomIn fast"

  [[params.navlinks]]
  name = "About"
  url = "/about/"

  [[params.navlinks]]
  name = "Projects"
  url = "/projects/"

  [[params.navlinks]]
  name = "Contact"
  url = "/contact/"

[params.console]
  title = "Kamil Noster"
  subtitle = "Software Developer"
  showHeader = true
  showMenu = true
  menuPosition = "right"
  showAppearanceSwitcher = true
  defaultTheme = "light"
  appearance = "light"
  appearanceSwitcherText = "🌙"
  appearanceSwitcherTextDark = "☀️"
  theme = "light"
  colorScheme = "light"
  defaultAppearance = "light" 